# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('image_url', models.TextField(default='/static/default.png')),
                ('line1', models.TextField(default='')),
                ('line2', models.TextField(default='')),
                ('line3', models.TextField(default='')),
            ],
        ),
    ]
