# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('image_url', models.TextField()),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
            ],
        ),
    ]
