# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161008_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='start_time',
        ),
        migrations.AddField(
            model_name='update',
            name='user_hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
