# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161008_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('image_url', models.TextField()),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
