# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_parseddata_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='image_url',
            field=models.TextField(default='/static/default.png'),
        ),
    ]
