# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161119_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseddata',
            name='line3',
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='line1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='line2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
