# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161119_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseddata',
            name='dirty',
        ),
        migrations.AddField(
            model_name='parseddata',
            name='line3',
            field=models.TextField(default=''),
        ),
    ]
